### ISSUE TITLE
Use another K8S API specific endpoint with gofabric8

### ISSUE THREAD

**Issue by ThomasSchweizer** [fabric8io/gofabric8#127]
Hello,
We are using Rancher for deploying our K8S cluster. Basically Rancher is deploying Kubernetes with only HTTP port 80 exposed so we have to access the API on _http://kubernetes:80_

When connecting to Fabric8 Webconsole I have a lot of errors in the fabric8 console logs because fabric8 is trying to call the API at _https://kubernetes:443_

I can access the K8S API in HTTPS but only over Rancher proxy
Basically to access the K8S API I have to connect to : **https://rancher.mycompany/r/projects/1a012/kubernetes/api/v1**

Any idea how can I set this during the gofabric8 deployment process?

Thank you for your advices :)
Best regards, Thomas

**Comment by jstrachan** [comment]
Note that the https://kubernetes:443 is using DNS to resolve the kubernetes service name "kubernetes" to the internal kubernetes service port IP. 

I wonder if the issue is that DNS isn't enabled so that kubernetes DNS name doesn't get resolved inside the fabric8 console pod? 

e.g. if you do

```
kubectl exec -it fabric8-1234 bash

$ curl -k https://kubernetes:443/
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/controllers",
    "/healthz",
    "/healthz/ping",
    "/healthz/ready",
    "/metrics",
    "/oapi",
    "/oapi/v1",
    "/swaggerapi/"
  ]
}
```

and you should get some JSON back as above. If that doesn't work it sounds like the kubernetes service DNS resolution isn't working?

**Comment by jstrachan** [comment]
incidentally what version of kubernetes is being used? I thought kubernetes was always exposed on 443?

As a temporary workaround you could edit the ReplicationController `fabric8` via `kubectl edit rc fabric8` to change this line:
```
      containers:
        - name: fabric8
          image: 'fabric8/fabric8-console:2.2.174'
          command:
            - /kuisp
            - '-p'
            - '9090'
            - '-c'
            - /site/osconsole/config.basic.js.tmpl=/site/osconsole/config.js
            - '--bearer-token=/var/run/secrets/kubernetes.io/serviceaccount/token'
            - '--skip-cert-validation=true'
            - '--default-page=/index.html'
            - '--max-age=24h'
            - '-s'
            - '/k8s/=https://kubernetes:443/'
```

to be 

```
            - '/k8s/=http://kubernetes:80/'
```

I'd like to figure out why 443 isn't allowed though. If we have to we can try figure out how to make that URL more easily configurable
