### ISSUE TITLE
message-broker fails to create PV

### ISSUE THREAD

**Issue by jeremy-wilson** [fabric8io/gofabric8#276]
I have a storage class setup.

```
cat <<EOF | kubectl create -f -
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: standard
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
EOF
```

When I installed the components of "management" for elastic search, prometheus, etc - the PV is automatically created because the PVC is set to use the "standard" StorageClass.

However, when installing "message-broker", it fails to start because it is expecting the PV to be there. 

The PVC is creating, however it is in a pending state as the PV has not been created. Looking at the definition in the UI, the config says it is supposed to be using the "standard" StorageClass but its still not being created.

There is one difference though. message-broker wants to use a claim set to 100Mi and the others are attempting to use it as 1Gi. But not sure if that would matter.

This is up on google.
