### ISSUE TITLE
invalid_request when hitting fabric8 web console

### ISSUE THREAD

**Issue by tsalopek** [fabric8io/gofabric8#34]
When attempting to access the fabric8 web console after installing fabric8 on an openshift instance, I am returned the following error in my browser:
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.","state":"https://my.domain.here/"}

It appears to be occurring following a redirect from the fabric8 console to an oauth authorize page.

**Comment by rawlingsj** [comment]
There's an `api-server` flag during gofabric8 deploy which might help if your domain is different from the openshift master api server..

for example...
```
gofabric8 deploy -y  --domain mydomain.fabric8.io --api-server masterapiserver.mydomain.fabric8.io
```

**Comment by tsalopek** [comment]
Our domain is not different than the master api server. Would you have any other suggestions?

Thanks!

**Comment by rawlingsj** [comment]
You could check the fabric8 `oauthclient` resource.  If you run the following, check you have a http and https RedirectURI entry that matches the domain that the console is running in.

```
oc export oauthclient fabric8
```

Here's an example of a cluster we use, with two different versions of the fabric8 console running in two OpenShift projects, `default` (domain origin.fabric8.io) and `cd` (domain cd.origin.fabric8.io). 

```
oc export oauthclient fabric8
apiVersion: v1
kind: OAuthClient
metadata:
  creationTimestamp: null
  name: fabric8
redirectURIs:
- http://localhost:9090
- http://localhost:2772
- http://localhost:9000
- http://fabric8.origin.fabric8.io
- https://fabric8.origin.fabric8.io
- http://fabric8.cd.origin.fabric8.io
- https://fabric8.cd.origin.fabric8.io
```
