### ISSUE TITLE
validation should check that there is enough PersistentVolume capability so that any RC using a PersistentVolumeClaim (e.g. Jenkins / Gerrit) can be created

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/gofabric8#6]
we should validate that there's enough PV capability available.

Also having a tool to create a PV entry would be cool! For a 1 node system we can just create a hostPath for now...

```
cat <<EOF | oc create -f -
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0001
spec:
  accessModes: 
    - ReadWrite
  capacity:
    storage: 90
  hostPath:
    path: /pvol/pv0001
EOF
```

for other kinds of PV implementation there could be different commands or a little CLI wizard to prompt for details (e.g. where Ceph / NFS is etc)
